addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: e71b8a35-64e8-4c9c-8219-48ace77e4a88
after_success:
- ./df-build.sh
before_install:
- sudo apt-get update -qq
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm
  ia32-libs ia32-libs-multiarch; fi
- wget https://dl-ssl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
- tar -zxf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
- export ANDROID_HOME=`pwd`/android-sdk-linux
- export ANDROID_BUILD_TOOLS_HOME=${ANDROID_HOME}/build-tools/17.0.0
- export PATH=${ANDROID_BUILD_TOOLS_HOME}:${ANDROID_HOME}/tools:${PATH}
- export BASEDIR=`pwd`
- mkdir -p ${ANDROID_BUILD_TOOLS_HOME}
- cd ${ANDROID_BUILD_TOOLS_HOME}
- export FILE=build-tools_${ANDROID_BUILD_TOOLS_VERSION}-linux.zip
- wget https://dl-ssl.google.com/android/repository/${FILE}
- unzip -q ${FILE}
- rm ${FILE}
- export FILE=$(ls)
- mv ${FILE}/* .
- rmdir ${FILE}
- cd ${BASEDIR}
- export FILE=android-14_r03.zip
- wget https://dl-ssl.google.com/android/repository/${FILE}
- mkdir -p ${ANDROID_HOME}/platforms
- unzip -q ${FILE} -d ${ANDROID_HOME}/platforms
- mv ${ANDROID_HOME}/platforms/android-4.0.2 ${ANDROID_HOME}/platforms/android-14
- rm ${FILE}
- unset FILE
- wget http://downloads.gradle.org/distributions/gradle-1.6-all.zip
- unzip -q -o gradle-1.6-all.zip
- export PATH="${BASEDIR}/gradle-1.6/bin:${PATH}"
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - ANDROID_SDK_VERSION="r22.0.1"
  - ANDROID_BUILD_TOOLS_VERSION="r17"
  - ANDROID_PLATFORM_TOOLS_VERSION="r17"
install: gradle build
jdk:
- openjdk7
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-stg.public-swarm.devfactory.com/travisWebHookListener?build_id=e71b8a35-64e8-4c9c-8219-48ace77e4a88
script: gradle check
# Modified by Insights Service at 2016-09-28 21:32:08.611119
